### ISSUE TITLE
Ensure proper termination

### ISSUE THREAD

**Issue by bhermann** [delphi-hub/delphi-cli#36]
**Describe the bug**
In cases where the server could not be reached the cli seemed to hang in some cases.

**To Reproduce**
1. Run `delphi` with a `--server` option not referring to a reachable server.
2. Observe

**Expected behavior**
The client should terminate.

**Screenshots**
None

**Affected components (if known)**
cli

**Desktop (please complete the following information, if relevant):**
n/a

**Smartphone (please complete the following information, if relevant):**
n/a

**Additional context**
none

**Comment by johannesduesing** [comment]
I have not been able to reproduce the issue on my machine so far. Tried non-existent host, servers with blocked ports and invalid protocols. The application terminated as expected, although there have been some uncaught exception stacks printed to the console.
Can you remember in which scenarios exactly the issue happend?

**Comment by bhermann** [comment]
It may have been fixed in conjunction with the change in the HTTP library.
