### ISSUE TITLE
Add download feature to CLI's search feature

### ISSUE THREAD

**Issue by bhermann** [delphi-hub/delphi-cli#43]
**Is your feature request related to a problem? Please describe.**
When a user executes a query via the CLI the goal is often to retrieve a set of artifacts for evaluation. Currently, the user has to resolve the needed URLs and files themselves. 

**Describe the solution you'd like**
The CLI should have an option to download the results of a query into a folder in an organized fashion. They should be able specify whether they would like to have only the metadata files, only the jar files, or both. The download should be accompanied with a data file describing the query used, the results considered, the versions of both client and server, url of the server used, and date/time of execution. 

**Describe alternatives you've considered**
none 

**Additional context**
none

**Comment by johannesduesing** [comment]
Closed with #45
