### ISSUE TITLE
Add a download feature to the CLI's retrieve feature

### ISSUE THREAD

**Issue by bhermann** [delphi-hub/delphi-cli#44]
**Is your feature request related to a problem? Please describe.**
When inspecting an artifact's available information users might want to retrieve the artifact itself too.,

**Describe the solution you'd like**
When executing a retrieve command for a specific artifact a user should be able to specify whether they would like to have the original artifact retrieved too. The download should be organized in a folder where it would not conflict with other download happening at another time or for a different artifact.
The download should be accompanied with a data file describing the retrieve query used, the results of this query, the versions of both client and server, url of the server used, and date/time of execution.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by johannesduesing** [comment]
Closed with #45
